Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -25,7 +25,14 @@ jobs:
       run: go build -v ./...
 
     - name: Test
+      continue-on-error: true
       run: go test -v ./...
+    - name: Error handling
+      if: ${{ steps.error_execution.outcome == 'failure' }}
+      run: |
+        echo "Error handling"
+        echo ${{ steps.error_execution.outcome }}
+        exit 1
   notify:
     runs-on: ubuntu-latest
     needs: [build]
